### PR TITLE
Entrega Hands On Assignment 5 - Grupo 02 

### PR DESCRIPTION
**Pull request by adrix1341**

### CODE REVIEW

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
Defining that your Address instances are the same as those Streets from Wikidata is ok, but if you say that an Address is the same as a District is wrong. 

A solution to add the data that you have retrieved from the reconciliation might be defining a new class in your ontology for defining District and a new relation to define a relation between Address and District. Then, regenerate your mapping with these changes. Then you can say that District instances of your RDF dataset are the same as those from Wikidata and define this link. (You will have to follow the same steps for Neighborhood, Province, and City).

Another solution might be to remove all these sameAs links from your mapping and leave only the correspoding with the Street. Then regenerate the RDF.

Please, fix the assigment and resubmit it.

**Comment by adrix1341** [comment]
Ya hemos cambiado la ontología añadiendo las clases y las relaciones de Province, District, City y Neighborhood, y por tanto también hemos actualizado los mappings y el output.

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
Ahora tiene mejor pinta! 
Solo un último comentario, en el mapping olvidaron incluir de qué clase son los nuevos Subjects que han incluido (e.g. [a, findparking:Address]. Pues tal como está ahora en el RDF las nuevas intancias no tienen definido de qué tipo son. 
Por favor, arreglar esto y reenviarlo.

**Comment by adrix1341** [comment]
Ya hemos incluido de que clase son los nuevos Subjects.

**Review by paoespinozarias — APPROVED** [review]

**Pull request merged**
