### PR TITLE
handsOn 5 and small updates

### PR DESCRIPTION
**Pull request by alvarogar4**
We have doubts about how the required ttl files is made. We don't know how to change the yml file to generate the rml. Because of that we couldn't test the sparql queries.

### CODE REVIEW

**Comment by alvarogar4** [comment]
We think that the problems are fixed.

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
Some comments about your submission:
- In the CSV you retrieved district_name's URI that are not correct because are instances of a SKOS:Concept class and you want instances from District (e.g. http://dbpedia.org/page/Chamart%C3%ADn_(Madrid)).  
- Your RDF file has duplicated values e.g. for the _hasStreet_ property. 
- The second SPARQL query should count the number of ?bikeSt instead of the ?nStations attribute that you didn't define in the query.
- You must add a query with the _sameAs_ predicate in order to get the new links that you included in your RDF data.

Please, fix these coments and resubmit your assignment.

**Comment by alvarogar4** [comment]
We have fixed everything but the second point. We don't know how to change that because our database has all this information repeated, and we think that we should change it there, but if we do that we should change everything. How could we solve that?

**Review by paoespinozarias — APPROVED** [review]
Now your assignment is ok! (Maybe in the last submission your NT file was wrong generated, but now I don't see any repeated values as I mentioned before)

Well done guys!

**Pull request merged**
