### PR TITLE
Hands on 2

### PR DESCRIPTION
**Pull request by JustAntoRS**
Also renamed folder Grupo44 to Group44 as asked.

### CODE REVIEW

**Comment by rgcmme** [comment]
There is a conflict in the pull request, remove it. The rest looks good.

**Comment by JustAntoRS** [comment]
Conflicts solved, sorry for the delay :)

**Comment by rgcmme** [comment]
Revert the change in this file, so you don't update it: HandsOn/Templates/selfAssessmentHandsOn2.md

**Comment by rgcmme** [comment]
Check whether this pull request is still needed after accepting the other one.

**Comment by JustAntoRS** [comment]
After checking it, the changes in this PR are already merged into master with another PR that added the files of handsOn2 and handsOn3.

**Pull request closed without merging**
