### PR TITLE
Handson4 (Group 12)

### PR DESCRIPTION
**Pull request by belenfh999**
We have updated the ontology, the resource naming strategy, the csv encoding, did the required tasks for this assignment but there's a problem with the join conditions because it generates triples incorrectly and we do not know how to fix it yet.

### CODE REVIEW

**Comment by dachafra** [comment]
let us talk about that issue during today's class ;-) 
btw, good work!

**Comment by dachafra** [comment]
Hi @belenfh999 
I did a test and you are right, it is not performing correctly the join condition... I resolved it adding the conditions to the matching sections.


[mapping.yaml.zip](https://github.com/FacultadInformatica-LinkedData/Curso2020-2021/files/5355428/mapping.yaml.zip)

**Comment by belenfh999** [comment]
Ohhh!! I was trying to fix it but I was thinking about doing a nested function or something complex like that. Thank you so much for your help!

**Comment by dachafra** [comment]
Perfect! nice work!

**Comment by dachafra** [comment]
> Ohhh!! I was trying to fix it but I was thinking about doing a nested function or something complex like that. Thank you so much for your help!

Now... I'm having a discussion with the RMLMapper developers because they interpreted the specification in a different way, and it is why you obtain that output ;-)

**Pull request merged**
