### PR TITLE
update assigment2 2.1

### PR DESCRIPTION
**Pull request by alvaroalvi**

### CODE REVIEW

**Comment by ocorcho** [comment]
Turtle is ok, but you still have a problem with the assignment 1 files. Try to sync first, and then do the pull request again.

**Comment by alvaroalvi** [comment]
profe no entiendo lo de sincronizarlo que es lo que esta mal??

**Comment by alvaroalvi** [comment]
mejor dicho como lo sincronizo, volviéndolo a enviar o como?

**Comment by alvaroalvi** [comment]
> Turtle is ok, but you still have a problem with the assignment 1 files. Try to sync first, and then do the pull request again.

profe no entiendo lo de la sincronizacion, que hay que hacer?

**Pull request closed without merging**
