### PR TITLE
Assignment 4

### PR DESCRIPTION
**Pull request by Frax7**

### CODE REVIEW

**Comment by rgcmme** [comment]
The assignment is not complete and it does not follow the requested formats.

**Comment by dachafra** [comment]
assignment4 ok

**Comment by Frax7** [comment]
I've changed the prints formats and added the xsd.string specification when using Literals, Let me know if more changes must be done.

**Comment by dachafra** [comment]
@Frax7 the issues @rgcmme mentioned are about HandsOn work, the RDFlib assignment is ok

**Comment by Frax7** [comment]
Oh ok, I've removed the folder corresponding to our group (Grupo44). I had some problems with the branches earlier, that's why it was there. Me and my team have already done all previous HandsOn assignments, and they are all merged.

**Comment by dachafra** [comment]
you are now removing files that are already in the repo. I would recommend you if you only want to add the files for assing4: remove your fork (under your username) and do it again, clone it and add only the files of the assignment4, and do a new PR. if you will do this, please close this PR.

**Pull request closed without merging**
