### PR TITLE
Assignment 3 & Assignment 4

### PR DESCRIPTION
**Pull request by jmdu99**

### CODE REVIEW

**Comment by dachafra** [comment]
This also contains the assignment4, already notified by @jmdu99 via email. Will be reviewed after @ocorcho reviews of assignment3

**Comment by ocorcho** [comment]
Assignment 3 is ok. Now @dachafra can review assignment 4.

**Review by ocorcho — APPROVED** [review]
Assingment 3 ok.

**Review by dachafra — APPROVED** [review]
Well done, assignment4 is ok

**Pull request merged**
