### PR TITLE
Hands on5 Group 44

### PR DESCRIPTION
**Pull request by JustAntoRS**

### CODE REVIEW

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
I have a couple of comments:
- You didn't generate a new column in your CSV with the values retrieved from Wikidata. 
- The mapping has a mistake, you need to add ~iri after providing the value of sameAs otherwise you will generate a string instead of a resource in your RDF as you did now.
Please, fix it and resubmit your assignment.

**Comment by JustAntoRS** [comment]
Thanks for the comments, we addressed them in the latests commits, is everything ok now? :smiley:

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
You added a new column "PROVINCE_REC" and included a string value instead of a Wikidata URI in the CSV (you did the same for the municipality). However, if you execute the new mapping in order to regenerate your RDF data it will give a wrong URI, because it is not a Wikipedia one. 

Anyway, my suggestion now is that in your specific case as you have the same value for all the columns only leave the previous mapping, I mean e.g. for the province [owl:sameAs, wiki:Q162620~iri]. But, please remember that you need to be careful in cases when you don't have the same value for all your columns since you will not be able to solve it in this way. That's why I requested you to do as we explained in class.

Then regenerate your RDF data and also submit it as I can review that your sameAs links are ok with these changes.

**Comment by JustAntoRS** [comment]
Thanks for the comment, It was super useful to understand what we were doing wrong. We updated it and It should be ok now 😃

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
Great! I see that you included Wikidata URIs in your CSV. However, as you will use the values from these columns you don't need to include _wiki:_ in your mapping to define the _sameAs_ predicate because you already have the URIs in your CSV. Thus, just leave the column name, e.g. _$(PROVINCE_REC)~iri_. Then regenerate the RDF data and resubmit the assignment.

**Pull request merged**
