### PR TITLE
Handson1 (Group 12)

### PR DESCRIPTION
**Pull request by belenfh999**
I tried to separate the assignment 4 files and the handsOn asignment by creating two branches, but somehow the assignment 4 files are still here commited. I am not sure about how to fix this

### CODE REVIEW

**Comment by ocorcho** [comment]
No worries, it will be dealt with separately by @rgcmme and @dachafra

**Comment by belenfh999** [comment]
Oh, the only problem is that since I created one branch for this hands-on exercise, right now I have two branches active, the master one and this one, it won't be a problem to merge these pull requests?

**Comment by belenfh999** [comment]
What I mean is that I have right now two pull requests, one for the assignment 4 (made on the master branch) which I opened yesterday and now this one (made on a new branch).

**Comment by rgcmme** [comment]
The hands-on part is OK; once the assignment is ready it can be merged.

**Comment by rgcmme** [comment]
After creating the branch and making the pull request, it you want to create another branch you have to check out first master, so you don't have the changes in the first branch included in the second one.

**Comment by belenfh999** [comment]
Ohhh I didn't checkout the master, that's why the assignments have been mixed, thanks for the feedback!! Next time I will do it correctly

**Comment by rgcmme** [comment]
Please, change the name of the directory; there is already a group 11.

**Pull request merged**
