### PR TITLE
Assignment4-updated

### PR DESCRIPTION
**Pull request by mdelucasg**
Tomorrow, I will try to do Task08.

### CODE REVIEW

**Comment by dachafra** [comment]
where is task07?

**Comment by mdelucasg** [comment]
I thought that Task07 was good in the previous Pull Request, so I did not change anything from it. Therefore, it should be in my Assignment04 directory.

**Review by dachafra — CHANGES_REQUESTED** [review]
Task08 is not correct
You have to find the triples in the second graph that have the properties vcard:Family and vcard:Given vcard:EMAIL that are NOT in the graph1 and add them to this one

**Comment by dachafra** [comment]
anyway, you are adding changes over your handsOn folder...

**Pull request merged**
