### PR TITLE
HandsOn4 Group09

### PR DESCRIPTION
**Pull request by patin9**
As the previous task, we've worked on this one together. It was easier for us to do it this way instead of dividing it among us.

### CODE REVIEW

**Review by dachafra — CHANGES_REQUESTED** [review]
Really nice work! Well done, congratulations.
It's almost right. For the Object Properties you have to do a relation between two TriplesMap, so you need to specify a join (not a simple predicateObjectMap as it is right now). As you made the first version pretty well I will encourage you to think how to do it, you have an example that could give you ideas in the template: https://github.com/FacultadInformatica-LinkedData/Curso2020-2021/blob/master/mapping-templates/template-yarrrml.yml#L24

If you have any question ask me via email or teams, good luck ;-)

**Review by dachafra — APPROVED** [review]

**Comment by dachafra** [comment]
I'm really happy with your work! Accepting PR....

**Comment by jmdu99** [comment]
> I'm really happy with your work! Accepting PR....

Thank you!!!
But we still have to upload the new output.nt 😂😂

**Comment by dachafra** [comment]
no problem, do a new PR with it, it shouldn't be bigger than 100MG as GitHub has that limitation.

**Pull request merged**
