### PR TITLE
Assignment4 and HandsOn1 Group04

### PR DESCRIPTION
**Pull request by andgom97**

### CODE REVIEW

**Comment by rgcmme** [comment]
There is already a group 04, please change the group number.

**Comment by andgom97** [comment]
We will be Group08 then

**Review by dachafra — CHANGES_REQUESTED** [review]
task08 and task09 are incomplete/incorrect, please if you aren't going to do them, remove the files from the commit, rest are ok

**Comment by andgom97** [comment]
The changes to files from Group08 was just to evict conflicts, I didn't change any of their integrity. Also, the files corresponding to the task08 and task09 were removed, sorry for that.

**Comment by andgom97** [comment]
I chose Group27 this time as Group08 was used also before. I hope this time no one chooses the same number.

**Pull request merged**
