### PR TITLE
Assigment 4 && HandsOn Group06

### PR DESCRIPTION
**Pull request by merysan1999**

### CODE REVIEW

**Comment by rgcmme** [comment]
The hands-on part looks good. Once the other assignments are finished it can be merged.

**Comment by merysan1999** [comment]
Oh! I made the pull request because I thought the assigment 4 was complete too. Which part/s do i have to change/are missing ?

**Comment by rgcmme** [comment]
Nothing is missing, only assignment 4 has to be reviewed

**Comment by merysan1999** [comment]
Okay, thank u :)

**Comment by dachafra** [comment]
Task06: VCARD is a common and shared vocabulary to define relations and information about people, it doesn't contain any property called WORK, so use another namespace to define that relation please, ns for example...

**Comment by dachafra** [comment]
The PR is going to be merged although there is that minor error.

**Pull request merged**
